name: front-prod-deploy

# PR 요청에 대해
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend # build steps의 run을 ./frontend 경로에서 실행

jobs:
  build:
    # close 이벤트 중 merge일 때만 동작 && label이 [front] (id: 3141723409) 일때만 동작
    if: (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.id, 3141723409))
        || github.event_name == 'workflow_dispatch'
    runs-on: deploy-runner
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          npm run build:prod
          tar -cvf deploy.tar ./frontend/build/

      #- name: Deploy
      #  run: aws s3 sync --delete ./build s3://jujeol-prod-deploy --metadata Cache-Control=max-age=15552000
        
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./frontend/deploy.tar"
          target: "/home/ubuntu/jujeol-jujeol/frontend/deploy"
